import type { Provider } from "@/types/provider"
import type { Business, FoodProfile } from "@/types/business"
import type { Property, ListingType, FurnishingStatus } from "@/types/property"
import type { ServiceCategorySlug } from "@/types/category"
import {
  parseTags,
  type FoodFormValues,
  type ListingFormValues,
  type PropertyFormValues,
} from "@/features/provider/listingSchema"
import { serviceCategories } from "@/data/serviceCategories"
import { FOOD_SERVICE_OPTIONS, deriveFoodCategory } from "@/config/food"

/**
 * Onboarding/edit form values -> domain object builders (Onboarding, extended
 * Phase 9D for Edit Listing). Kept in their own module, not inside a page
 * component, so both ListingFormPage (create) and EditListingPage (edit)
 * can share them without a component file exporting non-component values.
 */
export function buildProvider(values: ListingFormValues, id: string): Provider {
  const category = serviceCategories.find((c) => c.slug === values.category)
  return {
    id,
    name: values.name,
    category: (category?.slug ?? values.category) as ServiceCategorySlug,
    categoryLabel: category?.label ?? values.category,
    description: values.description,
    area: values.area,
    tags: parseTags(values.tagsInput),
    image: values.image,
  }
}

/** An empty Food form block — the starting point when a Business is switched to Food & Dining. */
export function emptyFoodFormValues(): FoodFormValues {
  return { categories: [], serviceOptions: [], hoursNote: "", menuHighlights: [], menuImage: undefined }
}

/** FoodProfile -> form values (edit prefill). Menu-highlight ids are dropped: they are regenerated by `buildFoodProfile`. */
export function foodProfileToFormValues(food: FoodProfile): FoodFormValues {
  return {
    categories: [...food.categories],
    serviceOptions: [...food.serviceOptions],
    hoursNote: food.hoursNote ?? "",
    menuHighlights: (food.menuHighlights ?? []).map((item) => ({
      name: item.name,
      section: item.section ?? "",
      description: item.description ?? "",
      price: item.price ?? "",
    })),
    menuImage: food.menuImage,
  }
}

/**
 * Form values -> FoodProfile. Optional text is normalized the same way the
 * rest of the builders do it (blank -> omitted); service options are stored
 * in canonical config order regardless of click order; the category order is
 * kept as chosen because the first one is the PRIMARY category.
 */
export function buildFoodProfile(values: FoodFormValues, listingId: string): FoodProfile {
  const menuHighlights = values.menuHighlights.map((item, index) => ({
    id: `${listingId}-mh-${index + 1}`,
    name: item.name,
    section: item.section || undefined,
    description: item.description || undefined,
    price: item.price || undefined,
  }))
  return {
    categories: values.categories,
    serviceOptions: FOOD_SERVICE_OPTIONS.map((option) => option.value).filter((option) =>
      values.serviceOptions.includes(option)
    ),
    hoursNote: values.hoursNote || undefined,
    menuHighlights: menuHighlights.length > 0 ? menuHighlights : undefined,
    menuImage: values.menuImage,
  }
}

/**
 * Builds a General or a Food & Dining business. A Food submission always
 * produces `vertical: "food"` + a `FoodProfile`, with `category` DERIVED from
 * the primary Food category (never typed) — it can never fall back to General
 * and lose its Food data (the union on `ListingFormValues` guarantees `food`
 * is present whenever `vertical` is "food").
 */
export function buildBusiness(values: ListingFormValues, id: string): Business {
  const base = {
    id,
    name: values.name,
    description: values.description,
    area: values.area,
    tags: parseTags(values.tagsInput),
    image: values.image,
  }
  if (values.vertical === "food") {
    const food = buildFoodProfile(values.food, id)
    return { ...base, vertical: "food", category: deriveFoodCategory(food.categories), food }
  }
  return { ...base, vertical: "general", category: values.category }
}

export function buildProperty(values: PropertyFormValues, id: string): Property {
  const bedrooms = values.bedrooms?.trim() ? Number(values.bedrooms) : undefined
  return {
    id,
    title: values.title,
    listingType: values.listingType as ListingType,
    propertyType: values.propertyType,
    price: values.price,
    area: values.area,
    description: values.description,
    bedrooms: bedrooms !== undefined && !Number.isNaN(bedrooms) ? bedrooms : undefined,
    furnished: values.furnished ? (values.furnished as FurnishingStatus) : undefined,
    tags: values.tagsInput ? parseTags(values.tagsInput) : [],
    image: values.image,
  }
}
